name: CI
on: [push, pull_request]
jobs:
 checks:
  name: Linters
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
      node-version: 16
   - run: npm ci --ignore-scripts
   - run: npm run lint
 build:
  name: Build
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
      node-version: 16
   - run: npm ci --ignore-scripts
   - run: npm run build:lib
